######################################################
#                Chart Collections                   #
######################################################

external_templates:
  repo: templates
  template_variables:
    collection_section: "01"

collections:
  AniDB Popular:
    summary: A collection of Popular Anime on AniDB
    anidb_popular: 30
    template:
      - name: customsync
      - name: chart_shared
        key: anidb

Newly Released Movies:
    sort_title: +01_3NewReleases
    sync_mode: sync
    smart_label: added.desc
    trakt_list: https://trakt.tv/users/giladg/lists/latest-releases
    summary: A collection of newly-released movies in cinema and on streaming services
    url_poster: https://i.imgur.com/D62EdJd.jpg
    url_background: https://wallpaperbat.com/img/23094-cinema-hd-wallpaper-top-free-cinema-hd-background.jpg
    visible_library: true
    visible_home: true
    visible_shared: true
